services:
  app:
    image: ghcr.io/chnnick/california-district-mapper:latest
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped
